# Generated by Django 5.2.5 on 2025-08-09 18:35

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_account_birthday_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
