# Generated by Django 5.2.5 on 2025-08-12 12:54

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_account_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
