# Generated by Django 5.2.5 on 2025-08-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_user_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
