# Generated by Django 5.2.5 on 2025-08-15 08:54

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('publish', django.db.models.manager.Manager()),
            ],
        ),
    ]
