# Generated by Django 5.2.5 on 2025-08-15 14:04

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 750], upload_to='post_images', verbose_name='تصویر')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان تصویر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'تصویر پست',
                'verbose_name_plural': 'تصویر پست ها',
            },
        ),
    ]
