# Generated by Django 5.2.5 on 2025-08-15 14:16

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_post_managers_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[600, 750], upload_to='post_images/%Y/%m/%d', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان تصویر'),
        ),
    ]
