# Generated by Django 5.2.5 on 2025-08-15 15:00

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_imagepost_image_alter_imagepost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=70, scale=None, size=[500, 500], upload_to='profile_images/%Y/%m', verbose_name='تصویر'),
        ),
    ]
