# Generated by Django 5.2.5 on 2025-08-21 11:23

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_post_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
