# Generated by Django 5.2.5 on 2025-08-23 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_comment_dislikes_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(choices=[('like', 'لایک'), ('dislike', 'دیس لایک')], related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که لایک کرده اند'),
        ),
    ]
