# Generated by Django 5.2.5 on 2025-08-23 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_remove_comment_dislikes_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که دیس لایک کرده اند'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که لایک کرده اند'),
        ),
    ]
